# Project Identification
sonar.projectKey=ml-pro-app
sonar.projectName=ml-pro-app
sonar.projectVersion=1.0

# Source Code
sonar.sources=.

# Encoding
sonar.sourceEncoding=UTF-8

# Python Version
sonar.python.version=3

# Exclude unnecessary folders
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/venv/**,**/dependency-check-report/**,**/.git/**

# Optional: Coverage report location
# sonar.python.coverage.reportPaths=coverage.xml